#Requires -Version 5.1
<#
    Detection.ps1 - generated by Intune Package Builder

    Two jobs, deliberately separated.

    Without arguments this is Intune's detection script. Intune's contract is
    binary: exit 0 with output on stdout means installed, anything else means
    not installed. The verdict comes only from the Detection rule in
    Configuration.psd1 - never from PATH, shortcuts, associations or context
    menus. Those are configuration the package applies, not evidence the
    application is present, and making Intune's verdict depend on them turns a
    missing shortcut into a reinstall loop.

    With -Report it prints a readable diagnostic covering everything the
    package configures, and always exits 0. That is for a technician at a
    machine, not for Intune.

    A configuration that cannot be read exits non-zero AND explains itself on
    stderr. Exiting silently would be byte-for-byte what "not installed" looks
    like, and Intune would reinstall forever with nothing to diagnose.
#>

param(
    # Print the full diagnostic report instead of the detection verdict.
    [switch]$Report
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

#<RUNTIME>

# =============================================================================

function Compare-DetectedVersion {
    <#
        Returns $true when the found version satisfies the configured one.
        An unparseable version on either side is reported as a mismatch rather
        than guessed at.
    #>
    param([string]$Found, [string]$Required, [string]$Comparison)

    if (-not $Required) { return $true }
    if (-not $Found) { return $false }

    $foundVersion = $null
    $requiredVersion = $null
    try { $foundVersion = [version]$Found } catch { return $false }
    try { $requiredVersion = [version]$Required } catch { return $false }

    if ($Comparison -eq 'Equals')      { return ($foundVersion -eq $requiredVersion) }
    if ($Comparison -eq 'GreaterThan') { return ($foundVersion -gt $requiredVersion) }
    return ($foundVersion -ge $requiredVersion)
}

function Get-DetectionResult {
    <#
        The primary rule, and only the primary rule.
        Returns @{ Installed; Detail; Version }.
    #>
    param([Parameter(Mandatory)]$Config)

    $detection = Get-ConfigValue -Record $Config -Key 'Detection'
    if (-not $detection) { throw 'Configuration.psd1 has no Detection section.' }

    $type = [string](Get-ConfigValue -Record $detection -Key 'Type')
    if (-not $type) { throw 'Configuration.psd1 has a Detection section but no Detection.Type.' }

    $path = [string](Get-ConfigValue -Record $detection -Key 'Path')
    $required = [string](Get-ConfigValue -Record $detection -Key 'Version')
    $comparison = [string](Get-ConfigValue -Record $detection -Key 'VersionComparison' -Default 'GreaterThanOrEqual')

    switch ($type.ToUpper()) {
        'FILE' {
            if (-not $path) { throw 'File detection needs Detection.Path.' }
            if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
                return @{ Installed = $false; Detail = "Not found: $path"; Version = '' }
            }

            $found = ''
            try { $found = [string](Get-Item -LiteralPath $path).VersionInfo.FileVersion } catch { $found = '' }

            if ($required -and -not (Compare-DetectedVersion -Found $found -Required $required -Comparison $comparison)) {
                return @{ Installed = $false; Detail = "Version $found does not satisfy $comparison $required"; Version = $found }
            }
            return @{ Installed = $true; Detail = $path; Version = $found }
        }

        'FOLDER' {
            if (-not $path) { throw 'Folder detection needs Detection.Path.' }
            if (-not (Test-Path -LiteralPath $path -PathType Container)) {
                return @{ Installed = $false; Detail = "Not found: $path"; Version = '' }
            }
            return @{ Installed = $true; Detail = $path; Version = '' }
        }

        'REGISTRY' {
            if (-not $path) { throw 'Registry detection needs Detection.Path.' }
            if (-not (Test-RegKey -Path $path)) {
                return @{ Installed = $false; Detail = "Not found: $path"; Version = '' }
            }
            return @{ Installed = $true; Detail = $path; Version = '' }
        }

        'MSI' {
            $productCode = [string](Get-ConfigValue -Record $Config -Key 'ProductCode')
            if (-not $productCode) { throw 'MSI detection needs ProductCode.' }

            foreach ($root in @(
                'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall',
                'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall'
            )) {
                $key = "$root\$productCode"
                if (Test-RegKey -Path $key) {
                    $found = [string](Get-RegValue -Path $key -Name 'DisplayVersion')
                    if ($required -and -not (Compare-DetectedVersion -Found $found -Required $required -Comparison $comparison)) {
                        return @{ Installed = $false; Detail = "Version $found does not satisfy $comparison $required"; Version = $found }
                    }
                    return @{ Installed = $true; Detail = $key; Version = $found }
                }
            }
            return @{ Installed = $false; Detail = "ProductCode not registered: $productCode"; Version = '' }
        }

        default {
            throw "Detection.Type '$type' is not valid. Use File, Folder, Registry or MSI."
        }
    }
}

# =============================================================================

try {
    $config = Get-PackageConfiguration -PackageRoot $ScriptDir
    $result = Get-DetectionResult -Config $config

    if (-not $Report) {
        # Intune's path. One line on stdout and exit 0, or silence and exit 1.
        if ($result.Installed) {
            Write-Output "Detected: $($result.Detail)"
            exit 0
        }
        exit 1
    }

    # ---------------------------------------------------- the report (-Report)
    $appName = [string](Get-ConfigValue -Record $config -Key 'ApplicationName')

    Write-Output ''
    Write-Output "Application: $appName"
    Write-Output "Installed: $($result.Installed)"
    $reportedVersion = $result.Version
    if (-not $reportedVersion) { $reportedVersion = [string](Get-ConfigValue -Record $config -Key 'Version') }
    Write-Output "Version: $reportedVersion"
    Write-Output "Executable: $(if ($result.Installed) { 'PASS' } else { "FAIL - $($result.Detail)" })"

    # Everything below is diagnostic. None of it affects the verdict above.
    $pathConfig = Get-ConfigValue -Record $config -Key 'Path'
    if ([bool](Get-ConfigValue -Record $pathConfig -Key 'Enabled' -Default $false)) {
        $value = [string](Get-ConfigValue -Record $pathConfig -Key 'Value')
        $scope = [string](Get-ConfigValue -Record $pathConfig -Key 'Scope' -Default 'Machine')
        $present = $false
        try { $present = Test-PathEntry -Entry $value -Scope $scope } catch { $present = $false }
        Write-Output "PATH: $(if ($present) { 'PASS' } else { 'FAIL' }) ($scope, $value)"
    }
    else { Write-Output 'PATH: not configured' }

    $associations = @(Get-ConfigValue -Record $config -Key 'FileAssociations' -Default @())
    if ($associations.Count -gt 0) {
        $missing = @()
        foreach ($association in $associations) {
            $extension = [string](Get-ConfigValue -Record $association -Key 'Extension')
            $progId = [string](Get-ConfigValue -Record $association -Key 'ProgId')
            if (-not $progId) { $progId = "$($appName -replace '[^A-Za-z0-9]', '')$($extension -replace '\.', '')" }
            if (-not (Test-RegKey -Path "$script:ClassesRoot\$progId")) { $missing += $extension }
        }
        Write-Output "Associations: $(if ($missing.Count -eq 0) { 'PASS' } else { "FAIL - missing $($missing -join ', ')" })"
    }
    else { Write-Output 'Associations: not configured' }

    $menus = @(Get-ConfigValue -Record $config -Key 'ContextMenus' -Default @())
    if ($menus.Count -gt 0) {
        $missing = @()
        foreach ($menu in $menus) {
            $verb = [string](Get-ConfigValue -Record $menu -Key 'Verb')
            $appliesTo = ([string](Get-ConfigValue -Record $menu -Key 'AppliesTo' -Default 'File')).ToUpper()
            $extensions = @(Get-ConfigValue -Record $menu -Key 'Extensions' -Default @())

            $roots = @()
            if ($appliesTo -eq 'FOLDER') { $roots += 'Folder' }
            elseif ($appliesTo -eq 'DIRECTORY') { $roots += 'Directory' }
            elseif ($appliesTo -eq 'ALLFILES') { $roots += '*' }
            elseif ($extensions.Count -gt 0) {
                foreach ($extension in $extensions) {
                    $normalized = [string]$extension
                    if ($normalized -and -not $normalized.StartsWith('.')) { $normalized = ".$normalized" }
                    if ($normalized) { $roots += $normalized }
                }
            }
            else { $roots += '*' }

            foreach ($root in $roots) {
                if (-not (Test-RegKey -Path "$script:ClassesRoot\$root\shell\$verb")) { $missing += "$root\$verb" }
            }
        }
        Write-Output "Context Menu: $(if ($missing.Count -eq 0) { 'PASS' } else { "FAIL - missing $($missing -join ', ')" })"
    }
    else { Write-Output 'Context Menu: not configured' }

    $shortcuts = @(Get-ConfigValue -Record $config -Key 'Shortcuts' -Default @())
    foreach ($location in @('Desktop', 'StartMenu')) {
        $wanted = @($shortcuts | Where-Object {
            ([string](Get-ConfigValue -Record $_ -Key 'Location' -Default 'Desktop')) -eq $location
        })
        $label = if ($location -eq 'Desktop') { 'Desktop Shortcut' } else { 'Start Menu Shortcut' }

        if ($wanted.Count -eq 0) { Write-Output "$label`: not configured"; continue }

        $missing = @()
        foreach ($shortcut in $wanted) {
            $shortcutPath = Get-ShortcutPath -Shortcut $shortcut
            if (-not (Test-ShortcutFile -Path $shortcutPath).Exists) { $missing += $shortcutPath }
        }
        Write-Output "$label`: $(if ($missing.Count -eq 0) { 'PASS' } else { "FAIL - missing $($missing -join ', ')" })"
    }

    $state = Get-PackageState -ApplicationName $appName
    if ($state) {
        Write-Output "Owned resources: $(@(Get-ConfigValue -Record $state -Key 'Resources' -Default @()).Count)"
    }
    else {
        Write-Output 'Owned resources: none recorded (uninstall would remove nothing)'
    }

    Write-Output ''
    exit 0
}
catch {
    # Never silent. A silent non-zero exit is indistinguishable from "not
    # installed", which sends Intune into a reinstall loop with nothing in the
    # log to explain it. Written directly rather than through Write-Error,
    # which wraps the text in a block that reads badly in an agent log.
    [Console]::Error.WriteLine("Detection could not run: $($_.Exception.Message)")
    exit 1
}
