#Requires -Version 5.1
<#
    Install.ps1 - generated by Intune Package Builder

    Intune runs this and nothing else:

        powershell.exe -ExecutionPolicy Bypass -NoProfile -File .\Install.ps1

    No installer arguments are passed on the command line. Configuration.psd1
    is the single authoritative source for them, so there is nowhere for a
    second set to come from and nothing to duplicate.

    Stages:
        1  Load the configuration
        2  Start logging
        3  Validate the installer
        4  Run the installer silently
        5  Check the exit code
        6  Configure PATH
        7  Configure file associations
        8  Configure context menus
        9  Create shortcuts
       10  Validate the installation
       11  Record what this package created
       12  Report

    Nothing in stages 6 to 9 runs until stage 5 confirms the installer
    succeeded, so a shortcut never points at an application that is not there.
#>

param()

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

#<RUNTIME>

# =============================================================================

$logFile = $null
$exitCode = 1

try {
    # ------------------------------------------------- 1. Load configuration
    $config = Get-PackageConfiguration -PackageRoot $ScriptDir
    $appName = [string](Get-ConfigValue -Record $config -Key 'ApplicationName')
    if (-not $appName) { throw 'Configuration.psd1 has no ApplicationName.' }

    # ------------------------------------------------------- 2. Start logging
    $logging = Get-ConfigValue -Record $config -Key 'Logging'
    if ([bool](Get-ConfigValue -Record $logging -Key 'Enabled' -Default $true)) {
        $logRoot = [string](Get-ConfigValue -Record $logging -Key 'Path' -Default 'C:\ProgramData\IntunePackageBuilder\Logs')
        $logFile = Join-WindowsPath (Join-WindowsPath $logRoot $appName) 'Install.log'
    }

    Write-PackageLog "=== Install started: $appName ===" $logFile
    Write-PackageLog "Version        : $(Get-ConfigValue -Record $config -Key 'Version')" $logFile
    Write-PackageLog "Context        : $(Get-CurrentIdentity)" $logFile
    Write-PackageLog "Process ID     : $PID" $logFile
    Write-PackageLog "PowerShell     : $($PSVersionTable.PSVersion)" $logFile

    if (-not (Test-RunningAsSystem)) {
        Write-PackageLog 'Not running as SYSTEM. Intune deploys in SYSTEM context, where HKCU and the user profile differ from what is visible here.' $logFile 'WARN'
    }

    # ---------------------------------------------------- 3. Validate installer
    $installerType = ([string](Get-ConfigValue -Record $config -Key 'InstallerType' -Default 'EXE')).ToUpper()
    $installerFile = [string](Get-ConfigValue -Record $config -Key 'InstallerFile')
    if (-not $installerFile) { throw 'Configuration.psd1 has no InstallerFile.' }

    $installerPath = Join-Path $ScriptDir $installerFile
    if (-not (Test-Path -LiteralPath $installerPath)) {
        $present = @(Get-ChildItem -LiteralPath $ScriptDir -File -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty Name)
        throw "Installer not found: $installerFile. The package contains: $($present -join ', ')"
    }

    $installArguments = [string](Get-ConfigValue -Record $config -Key 'InstallArguments')
    $command = New-InstallerCommand -Type $installerType -InstallerPath $installerPath -Arguments $installArguments

    Write-PackageLog "Installer      : $installerFile ($installerType)" $logFile
    Write-PackageLog "Arguments      : $(if ($installArguments) { $installArguments } else { '(none)' })" $logFile
    Write-PackageLog "Command        : $($command.Display)" $logFile

    # ----------------------------------------------------- 4. Run the installer
    $process = Start-InstallerProcess -Command $command
    $installerExit = $process.ExitCode

    # ------------------------------------------------------- 5. Check exit code
    Write-PackageLog "Exit code      : $installerExit" $logFile

    $successCodes = @(Get-ConfigValue -Record $config -Key 'SuccessExitCodes' -Default @(0, 3010))
    if ($successCodes.Count -eq 0) { $successCodes = @(0, 3010) }

    if ($successCodes -notcontains $installerExit) {
        Write-PackageLog "The installer failed with exit code $installerExit. Configured success codes: $($successCodes -join ', ')." $logFile 'ERROR'
        Write-PackageLog '=== Install FAILED ===' $logFile 'ERROR'
        exit 1
    }

    # Everything past here was created by this package, and uninstall removes
    # exactly what is recorded in this list.
    $owned = @()
    $failures = @()

    # -------------------------------------------------------- 6. Configure PATH
    $pathConfig = Get-ConfigValue -Record $config -Key 'Path'
    if ([bool](Get-ConfigValue -Record $pathConfig -Key 'Enabled' -Default $false)) {
        $pathValue = [string](Get-ConfigValue -Record $pathConfig -Key 'Value')
        $pathScope = [string](Get-ConfigValue -Record $pathConfig -Key 'Scope' -Default 'Machine')

        if (-not $pathValue) {
            $failures += 'PATH is enabled but Path.Value is empty.'
        }
        else {
            if ($pathScope -eq 'User' -and (Test-RunningAsSystem)) {
                Write-PackageLog 'User PATH from SYSTEM context reaches the system profile, not any real user. Machine scope is normally what an Intune deployment wants.' $logFile 'WARN'
            }

            Write-PackageLog "PATH before    : $(Get-PersistentPath -Scope $pathScope)" $logFile
            $result = Add-PathEntry -Entry $pathValue -Scope $pathScope
            Write-PackageLog "PATH change    : $($result.Message)" $logFile

            if (-not $result.Success) { $failures += $result.Message }
            if ($result.Action -eq 'Added') {
                $owned += @{ Kind = 'Path'; Value = $pathValue; Scope = $pathScope; PreExisting = $false }
            }
            Write-PackageLog "PATH after     : $(Get-PersistentPath -Scope $pathScope)" $logFile
        }
    }

    # -------------------------------------------- 7. Configure file associations
    foreach ($association in @(Get-ConfigValue -Record $config -Key 'FileAssociations' -Default @())) {
        $extension = [string](Get-ConfigValue -Record $association -Key 'Extension')
        $executable = [string](Get-ConfigValue -Record $association -Key 'Executable')
        if (-not $extension -or -not $executable) {
            $failures += 'A file association is missing its Extension or Executable.'
            continue
        }

        $progId = [string](Get-ConfigValue -Record $association -Key 'ProgId')
        if (-not $progId) { $progId = "$($appName -replace '[^A-Za-z0-9]', '')$($extension -replace '\.', '')" }

        $progIdKey = "$script:ClassesRoot\$progId"
        $extensionKey = "$script:ClassesRoot\$extension"

        try {
            $progIdExisted = Test-RegKey -Path $progIdKey

            Set-RegValue -Path $progIdKey -Name '' -Value ([string](Get-ConfigValue -Record $association -Key 'Description'))
            $icon = [string](Get-ConfigValue -Record $association -Key 'Icon')
            if ($icon) { Set-RegValue -Path "$progIdKey\DefaultIcon" -Name '' -Value $icon }
            Set-RegValue -Path "$progIdKey\shell\open\command" -Name '' -Value "`"$executable`" `"%1`""

            if (-not $progIdExisted) {
                $owned += @{ Kind = 'RegistryKey'; Path = $progIdKey; PreExisting = $false }
            }

            # Offering the application under "Open with" adds it without
            # displacing whatever currently owns the extension.
            Set-RegValue -Path "$extensionKey\OpenWithProgids" -Name $progId -Value ''
            $owned += @{ Kind = 'RegistryValue'; Path = "$extensionKey\OpenWithProgids"; Name = $progId; PreExisting = $false }

            if ([bool](Get-ConfigValue -Record $association -Key 'SetAsDefault' -Default $false)) {
                $previous = Get-RegValue -Path $extensionKey -Name ''
                Set-RegValue -Path $extensionKey -Name '' -Value $progId
                # PreExisting is false on purpose: this package changed the
                # value, so it owns the change and must undo it. Whether there
                # was a value before is carried by PreviousValue.
                $owned += @{ Kind = 'RegistryDefault'; Path = $extensionKey; PreviousValue = $previous; PreExisting = $false }
                Write-PackageLog "Association    : $extension default set to $progId (was '$previous')" $logFile
            }

            Write-PackageLog "Association    : $extension -> $progId" $logFile
        }
        catch {
            $failures += "Could not register $extension`: $($_.Exception.Message)"
        }
    }

    # ------------------------------------------------ 8. Configure context menus
    foreach ($menu in @(Get-ConfigValue -Record $config -Key 'ContextMenus' -Default @())) {
        $verb = [string](Get-ConfigValue -Record $menu -Key 'Verb')
        $menuCommand = [string](Get-ConfigValue -Record $menu -Key 'Command')
        if (-not $verb -or -not $menuCommand) {
            $failures += 'A context menu entry is missing its Verb or Command.'
            continue
        }

        $appliesTo = ([string](Get-ConfigValue -Record $menu -Key 'AppliesTo' -Default 'File')).ToUpper()
        $extensions = @(Get-ConfigValue -Record $menu -Key 'Extensions' -Default @())

        $roots = @()
        if ($appliesTo -eq 'FOLDER') { $roots += 'Folder' }
        elseif ($appliesTo -eq 'DIRECTORY') { $roots += 'Directory' }
        elseif ($appliesTo -eq 'ALLFILES') { $roots += '*' }
        elseif ($extensions.Count -gt 0) {
            foreach ($extension in $extensions) {
                $normalized = [string]$extension
                if ($normalized -and -not $normalized.StartsWith('.')) { $normalized = ".$normalized" }
                if ($normalized) { $roots += $normalized }
            }
        }
        else { $roots += '*' }

        foreach ($root in $roots) {
            $verbKey = "$script:ClassesRoot\$root\shell\$verb"

            # An existing verb belongs to whoever put it there. Overwriting it
            # breaks their integration and leaves nothing to restore.
            if (Test-RegKey -Path $verbKey) {
                Write-PackageLog "Context menu   : $verbKey already exists and is left as it is" $logFile
                continue
            }

            try {
                Set-RegValue -Path $verbKey -Name '' -Value ([string](Get-ConfigValue -Record $menu -Key 'Name'))
                $icon = [string](Get-ConfigValue -Record $menu -Key 'Icon')
                if ($icon) { Set-RegValue -Path $verbKey -Name 'Icon' -Value $icon }
                Set-RegValue -Path "$verbKey\command" -Name '' -Value $menuCommand

                $owned += @{ Kind = 'RegistryKey'; Path = $verbKey; PreExisting = $false }
                Write-PackageLog "Context menu   : $verbKey" $logFile
            }
            catch {
                $failures += "Could not register the context menu verb $verb`: $($_.Exception.Message)"
            }
        }
    }

    # ---------------------------------------------------- 9. Create shortcuts
    foreach ($shortcut in @(Get-ConfigValue -Record $config -Key 'Shortcuts' -Default @())) {
        $name = [string](Get-ConfigValue -Record $shortcut -Key 'Name')
        $target = [string](Get-ConfigValue -Record $shortcut -Key 'Target')
        if (-not $name -or -not $target) {
            $failures += 'A shortcut is missing its Name or Target.'
            continue
        }

        # A shortcut to something that is not there looks installed and fails
        # when clicked, which is worse than no shortcut.
        $targetExists = $false
        try { $targetExists = Test-Path -LiteralPath $target } catch { $targetExists = $false }
        if (-not $targetExists) {
            $failures += "Shortcut target does not exist: $target"
            continue
        }

        $shortcutPath = Get-ShortcutPath -Shortcut $shortcut
        $existed = (Test-ShortcutFile -Path $shortcutPath).Exists

        try {
            New-ShortcutFile -Path $shortcutPath -Target $target `
                -Arguments ([string](Get-ConfigValue -Record $shortcut -Key 'Arguments')) `
                -WorkingDirectory ([string](Get-ConfigValue -Record $shortcut -Key 'WorkingDirectory')) `
                -Icon ([string](Get-ConfigValue -Record $shortcut -Key 'Icon'))

            $check = Test-ShortcutFile -Path $shortcutPath -ExpectedTarget $target
            if (-not $check.Exists) {
                $failures += "Shortcut was not created: $shortcutPath"
                continue
            }
            if (-not $check.TargetMatches) {
                $failures += "Shortcut points at '$($check.Target)' rather than '$target'."
                continue
            }

            $owned += @{ Kind = 'Shortcut'; Path = $shortcutPath; PreExisting = $existed }
            Write-PackageLog "Shortcut       : $shortcutPath -> $target" $logFile
        }
        catch {
            $failures += "Could not create the shortcut $shortcutPath`: $($_.Exception.Message)"
        }
    }

    # Tell Windows about the shell changes, if there were any.
    $touchedShell = @($owned | Where-Object { $_.Kind -like 'Registry*' })
    if ($touchedShell.Count -gt 0) {
        $notify = Update-ShellAssociations
        Write-PackageLog "Shell          : $($notify.Message)" $logFile
    }
    $touchedPath = @($owned | Where-Object { $_.Kind -eq 'Path' })
    if ($touchedPath.Count -gt 0) {
        $broadcast = Send-EnvironmentChange
        Write-PackageLog "Environment    : $($broadcast.Message)" $logFile
    }

    # ------------------------------------------------ 10. Validate the install
    $detectionScript = Join-Path $ScriptDir 'Detection.ps1'
    $detected = $false
    if (Test-Path -LiteralPath $detectionScript) {
        & $detectionScript | Out-Null
        $detected = ($LASTEXITCODE -eq 0)
    }
    else {
        Write-PackageLog 'Detection.ps1 is missing from the package, so the installation could not be verified.' $logFile 'WARN'
    }
    Write-PackageLog "Detection      : $(if ($detected) { 'PASS' } else { 'FAIL' })" $logFile

    # ------------------------------------------------- 11. Record what we own
    Save-PackageState -ApplicationName $appName -Resources $owned | Out-Null
    Write-PackageLog "Recorded       : $($owned.Count) resource(s) owned by this package" $logFile

    # ------------------------------------------------------------ 12. Report
    foreach ($failure in $failures) { Write-PackageLog $failure $logFile 'ERROR' }

    if (-not $detected) {
        Write-PackageLog 'The installer reported success but the application was not detected afterwards.' $logFile 'ERROR'
        Write-PackageLog '=== Install FAILED ===' $logFile 'ERROR'
        exit 1
    }

    if ($failures.Count -gt 0) {
        Write-PackageLog "The application installed, but $($failures.Count) configuration step(s) failed." $logFile 'ERROR'
        Write-PackageLog '=== Install FAILED ===' $logFile 'ERROR'
        exit 1
    }

    Write-PackageLog '=== Install SUCCEEDED ===' $logFile
    if ($installerExit -eq 3010) { exit 3010 }
    exit 0
}
catch {
    Write-PackageLog "Install failed: $($_.Exception.Message)" $logFile 'ERROR'
    Write-PackageLog '=== Install FAILED ===' $logFile 'ERROR'
    exit 1
}
