#Requires -Version 5.1
<#
    Uninstall.ps1 - generated by Intune Package Builder

    Intune runs this and nothing else:

        powershell.exe -ExecutionPolicy Bypass -NoProfile -File .\Uninstall.ps1

    Stages:
        1  Load the configuration
        2  Start logging
        3  Run the application's silent uninstall
        4  Remove the PATH entry this package added
        5  Remove the file associations this package registered
        6  Remove the context menu entries this package registered
        7  Remove the shortcuts this package created
        8  Verify the cleanup
        9  Report

    Every removal is driven by the ownership recorded at install time. Nothing
    is removed because it merely exists: a shortcut, key or PATH entry this
    package did not create is left alone. With no state file nothing is
    removed at all, and the fact is logged - a leftover shortcut is
    recoverable, another product's deleted registry key is not.
#>

param()

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

#<RUNTIME>

# =============================================================================

$logFile = $null

try {
    # ------------------------------------------------- 1. Load configuration
    $config = Get-PackageConfiguration -PackageRoot $ScriptDir
    $appName = [string](Get-ConfigValue -Record $config -Key 'ApplicationName')
    if (-not $appName) { throw 'Configuration.psd1 has no ApplicationName.' }

    # ------------------------------------------------------- 2. Start logging
    $logging = Get-ConfigValue -Record $config -Key 'Logging'
    if ([bool](Get-ConfigValue -Record $logging -Key 'Enabled' -Default $true)) {
        $logRoot = [string](Get-ConfigValue -Record $logging -Key 'Path' -Default 'C:\ProgramData\IntunePackageBuilder\Logs')
        $logFile = Join-WindowsPath (Join-WindowsPath $logRoot $appName) 'Uninstall.log'
    }

    Write-PackageLog "=== Uninstall started: $appName ===" $logFile
    Write-PackageLog "Context        : $(Get-CurrentIdentity)" $logFile
    Write-PackageLog "Process ID     : $PID" $logFile

    # ------------------------------------------------ 3. Run the uninstaller
    $installerType = ([string](Get-ConfigValue -Record $config -Key 'InstallerType' -Default 'EXE')).ToUpper()
    $uninstallArguments = [string](Get-ConfigValue -Record $config -Key 'UninstallArguments')
    $productCode = [string](Get-ConfigValue -Record $config -Key 'ProductCode')

    $uninstallExit = 0

    if ($installerType -eq 'MSI') {
        if (-not $productCode) { throw 'An MSI package needs ProductCode to uninstall.' }
        $arguments = "/x $productCode"
        if ($uninstallArguments) { $arguments = "$arguments $uninstallArguments" }
        else { $arguments = "$arguments /qn /norestart" }

        Write-PackageLog "Command        : msiexec.exe $arguments" $logFile
        $process = Start-Process -FilePath 'msiexec.exe' -ArgumentList $arguments -Wait -PassThru -NoNewWindow
        $uninstallExit = $process.ExitCode
    }
    else {
        $installerFile = [string](Get-ConfigValue -Record $config -Key 'InstallerFile')
        $installerPath = Join-Path $ScriptDir $installerFile

        if (-not (Test-Path -LiteralPath $installerPath)) {
            Write-PackageLog "The installer is not in the package, so the application's own uninstall cannot run: $installerFile" $logFile 'WARN'
            Write-PackageLog 'Continuing with the cleanup of what this package created.' $logFile 'WARN'
        }
        else {
            $command = New-InstallerCommand -Type $installerType -InstallerPath $installerPath -Arguments $uninstallArguments
            Write-PackageLog "Command        : $($command.Display)" $logFile
            $process = Start-InstallerProcess -Command $command
            $uninstallExit = $process.ExitCode
        }
    }

    Write-PackageLog "Exit code      : $uninstallExit" $logFile

    $successCodes = @(Get-ConfigValue -Record $config -Key 'SuccessExitCodes' -Default @(0, 3010))
    if ($successCodes.Count -eq 0) { $successCodes = @(0, 3010) }

    if ($successCodes -notcontains $uninstallExit) {
        Write-PackageLog "The uninstaller failed with exit code $uninstallExit." $logFile 'ERROR'
        Write-PackageLog '=== Uninstall FAILED ===' $logFile 'ERROR'
        exit 1
    }

    # ----------------------------------------- 4 to 7. Remove what we created
    $state = Get-PackageState -ApplicationName $appName
    $failures = @()

    if (-not $state) {
        Write-PackageLog 'No ownership was recorded for this package, so nothing is removed. Ownership cannot be established, and removing another product resource is not recoverable.' $logFile 'WARN'

        # A machine installed by the previous framework has state this package
        # cannot read. Say so by name rather than leaving PATH entries behind
        # silently.
        $legacy = Get-LegacyPackageState -ApplicationName $appName
        if ($legacy) {
            Write-PackageLog "Ownership from an earlier build of this package exists at $($legacy.Path)." $logFile 'WARN'
            foreach ($entry in @($legacy.Machine)) {
                Write-PackageLog "  Machine PATH entry recorded there, not removed: $entry" $logFile 'WARN'
            }
            foreach ($entry in @($legacy.User)) {
                Write-PackageLog "  User PATH entry recorded there, not removed: $entry" $logFile 'WARN'
            }
        }
    }
    else {
        $resources = @(Get-ConfigValue -Record $state -Key 'Resources' -Default @())
        Write-PackageLog "Removing       : $($resources.Count) recorded resource(s)" $logFile

        foreach ($resource in $resources) {
            $kind = [string](Get-ConfigValue -Record $resource -Key 'Kind')
            $path = [string](Get-ConfigValue -Record $resource -Key 'Path')
            $preExisting = [bool](Get-ConfigValue -Record $resource -Key 'PreExisting' -Default $false)

            if ($preExisting) {
                Write-PackageLog "Left in place  : $kind $path (it existed before this package)" $logFile
                continue
            }

            try {
                if ($kind -eq 'Path') {
                    $value = [string](Get-ConfigValue -Record $resource -Key 'Value')
                    $scope = [string](Get-ConfigValue -Record $resource -Key 'Scope' -Default 'Machine')
                    Write-PackageLog "PATH before    : $(Get-PersistentPath -Scope $scope)" $logFile
                    $result = Remove-PathEntry -Entry $value -Scope $scope
                    Write-PackageLog "PATH change    : $($result.Message)" $logFile
                    Write-PackageLog "PATH after     : $(Get-PersistentPath -Scope $scope)" $logFile
                    if (-not $result.Success) { $failures += $result.Message }
                }
                elseif ($kind -eq 'Shortcut') {
                    Remove-ShortcutFile -Path $path
                    Write-PackageLog "Removed        : shortcut $path" $logFile
                }
                elseif ($kind -eq 'RegistryKey') {
                    Remove-RegKey -Path $path
                    Write-PackageLog "Removed        : registry key $path" $logFile
                }
                elseif ($kind -eq 'RegistryValue') {
                    $name = [string](Get-ConfigValue -Record $resource -Key 'Name')
                    Remove-RegValue -Path $path -Name $name
                    Write-PackageLog "Removed        : registry value $path\$name" $logFile
                }
                elseif ($kind -eq 'RegistryDefault') {
                    # This package replaced an extension's default handler.
                    # Put back exactly what was there.
                    $previous = [string](Get-ConfigValue -Record $resource -Key 'PreviousValue')
                    if ($previous) {
                        Set-RegValue -Path $path -Name '' -Value $previous
                        Write-PackageLog "Restored       : default handler for $path to '$previous'" $logFile
                    }
                    else {
                        Remove-RegValue -Path $path -Name '(default)'
                        Write-PackageLog "Cleared        : the default handler this package set on $path" $logFile
                    }
                }
                else {
                    Write-PackageLog "Unknown resource kind in the state file, left alone: $kind" $logFile 'WARN'
                }
            }
            catch {
                $failures += "Could not remove $kind '$path': $($_.Exception.Message)"
            }
        }

        $touchedShell = @($resources | Where-Object { [string](Get-ConfigValue -Record $_ -Key 'Kind') -like 'Registry*' })
        if ($touchedShell.Count -gt 0) {
            $notify = Update-ShellAssociations
            Write-PackageLog "Shell          : $($notify.Message)" $logFile
        }
        $touchedPath = @($resources | Where-Object { [string](Get-ConfigValue -Record $_ -Key 'Kind') -eq 'Path' })
        if ($touchedPath.Count -gt 0) {
            $broadcast = Send-EnvironmentChange
            Write-PackageLog "Environment    : $($broadcast.Message)" $logFile
        }

        Remove-PackageState -ApplicationName $appName
    }

    # ------------------------------------------------- 8. Verify the cleanup
    $detectionScript = Join-Path $ScriptDir 'Detection.ps1'
    $stillDetected = $false
    if (Test-Path -LiteralPath $detectionScript) {
        & $detectionScript | Out-Null
        $stillDetected = ($LASTEXITCODE -eq 0)
    }
    Write-PackageLog "Detection      : $(if ($stillDetected) { 'still installed' } else { 'not installed' })" $logFile

    # ------------------------------------------------------------- 9. Report
    foreach ($failure in $failures) { Write-PackageLog $failure $logFile 'ERROR' }

    if ($stillDetected) {
        Write-PackageLog 'The application is still detected after uninstalling.' $logFile 'ERROR'
        Write-PackageLog '=== Uninstall FAILED ===' $logFile 'ERROR'
        exit 1
    }

    if ($failures.Count -gt 0) {
        Write-PackageLog "The application was removed, but $($failures.Count) cleanup step(s) failed." $logFile 'ERROR'
        Write-PackageLog '=== Uninstall FAILED ===' $logFile 'ERROR'
        exit 1
    }

    Write-PackageLog '=== Uninstall SUCCEEDED ===' $logFile
    if ($uninstallExit -eq 3010) { exit 3010 }
    exit 0
}
catch {
    Write-PackageLog "Uninstall failed: $($_.Exception.Message)" $logFile 'ERROR'
    Write-PackageLog '=== Uninstall FAILED ===' $logFile 'ERROR'
    exit 1
}
