#Requires -Version 5.1

<#
    Generator.ps1

    Produces the package source directory that becomes the .intunewin.

    The generated scripts are produced by splicing one maintained runtime into
    one maintained template - not by assembling script text per package. That
    matters for two reasons: a fix to PATH handling is one edit rather than one
    per code path, and every package is the same program to debug rather than a
    near-copy with its own quirks.

    What ships:

        PackageSource\
        ├── <installer>
        ├── Install.ps1
        ├── Uninstall.ps1
        ├── Detection.ps1
        └── Configuration.psd1

    Nothing else. The builder, its templates and its tests stay out of the
    package - IntuneWinAppUtil archives everything beneath the folder it is
    given, so anything left there is delivered to every managed machine.
#>

$script:RuntimeMarker = '#<RUNTIME>'

function Get-TemplateDirectory {
    return (Join-Path (Split-Path -Parent $PSCommandPath) 'Templates')
}

function Get-PackageScriptNames {
    return @('Install.ps1', 'Uninstall.ps1', 'Detection.ps1')
}

function Build-PackageScript {
    <#
        .SYNOPSIS
        Returns one generated script as text, with the runtime spliced in.

        .DESCRIPTION
        The marker is replaced rather than appended to, so the runtime lands
        above the main body and the functions exist before anything calls
        them. A template without the marker is a mistake in the builder, not
        something to paper over, so it throws.
    #>
    param(
        [Parameter(Mandatory)][ValidateSet('Install.ps1', 'Uninstall.ps1', 'Detection.ps1')]
        [string]$Name,
        [string]$BuilderVersion = ''
    )

    $templateDirectory = Get-TemplateDirectory
    $templatePath = Join-Path $templateDirectory $Name
    $runtimePath = Join-Path $templateDirectory '_Runtime.ps1'

    foreach ($required in @($templatePath, $runtimePath)) {
        if (-not (Test-Path -LiteralPath $required)) {
            throw "The builder is incomplete: $required is missing."
        }
    }

    $template = Get-Content -LiteralPath $templatePath -Raw
    if (-not $template.Contains($script:RuntimeMarker)) {
        throw "$Name has no $script:RuntimeMarker marker, so the runtime has nowhere to go."
    }

    $runtime = Get-Content -LiteralPath $runtimePath -Raw

    # The runtime's own #Requires would land mid-file, where PowerShell rejects
    # it. It is already declared at the top of every template.
    $runtime = ($runtime -replace '(?m)^#Requires[^\r\n]*\r?\n', '')

    $stamp = $BuilderVersion
    if (-not $stamp) { $stamp = 'unknown' }
    $banner = @"
# -----------------------------------------------------------------------------
# Generated by Intune Package Builder $stamp on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#
# Do not edit this file. It is regenerated whenever the package is built, and
# every change made here is lost. Edit the configuration instead.
# -----------------------------------------------------------------------------
"@

    # String.Replace, not -replace. The regex operator treats the runtime as a
    # replacement pattern, where every backslash in a Windows path and every $
    # in a variable name is a substitution directive. A literal replace has no
    # such reading of its input.
    return $template.Replace($script:RuntimeMarker, ($banner + [Environment]::NewLine + $runtime))
}

function New-PackageSource {
    <#
        .SYNOPSIS
        Writes the complete package source directory.

        .PARAMETER InstallerPath
        The real installer, copied in under the name the configuration
        expects.

        .PARAMETER OutputPath
        The directory to create. It is emptied of previously generated files
        first, so a rename does not leave the old installer behind for
        IntuneWinAppUtil to archive alongside the new one.

        .OUTPUTS
        @{ Path; Files; Warnings }
    #>
    param(
        [Parameter(Mandatory)]$Config,
        [Parameter(Mandatory)][string]$InstallerPath,
        [Parameter(Mandatory)][string]$OutputPath,
        [string]$BuilderVersion = ''
    )

    if (-not (Test-Path -LiteralPath $InstallerPath)) {
        throw "Installer not found: $InstallerPath"
    }

    $installerFile = [string]$Config.InstallerFile
    if (-not $installerFile) {
        throw 'The configuration has no InstallerFile, so the installer has no name to be copied to.'
    }

    $warnings = @()

    if (-not (Test-Path -LiteralPath $OutputPath)) {
        New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
    }
    else {
        # Only what this generator produces is cleared. Anything else the
        # technician put there is left alone and reported, because silently
        # archiving a stray file into every endpoint's package is worse than
        # saying so.
        foreach ($name in (Get-PackageScriptNames + 'Configuration.psd1')) {
            $stale = Join-Path $OutputPath $name
            if (Test-Path -LiteralPath $stale) { Remove-Item -LiteralPath $stale -Force }
        }

        $expected = @(Get-PackageScriptNames) + @('Configuration.psd1', $installerFile)
        foreach ($item in @(Get-ChildItem -LiteralPath $OutputPath -File -ErrorAction SilentlyContinue)) {
            if ($expected -notcontains $item.Name) {
                $warnings += "$($item.Name) is in the package directory but is not part of the package. It will be archived into the .intunewin."
            }
        }
    }

    $written = @()

    # The installer, under the name the configuration refers to.
    $installerDestination = Join-Path $OutputPath $installerFile
    $sourceFull = (Resolve-Path -LiteralPath $InstallerPath).Path
    $destinationFull = [System.IO.Path]::GetFullPath($installerDestination)
    if ($sourceFull -ne $destinationFull) {
        Copy-Item -LiteralPath $InstallerPath -Destination $installerDestination -Force
    }
    $written += $installerFile

    # The three scripts.
    foreach ($name in Get-PackageScriptNames) {
        $text = Build-PackageScript -Name $name -BuilderVersion $BuilderVersion
        $target = Join-Path $OutputPath $name
        [System.IO.File]::WriteAllText($target, $text, (New-Object System.Text.UTF8Encoding($false)))
        $written += $name
    }

    # The configuration.
    Export-PackageConfig -Config $Config -Path (Join-Path $OutputPath 'Configuration.psd1') | Out-Null
    $written += 'Configuration.psd1'

    return @{ Path = $OutputPath; Files = $written; Warnings = $warnings }
}

function Test-GeneratedScripts {
    <#
        .SYNOPSIS
        Confirms every generated script parses, and that the runtime actually
        landed in each one.

        .DESCRIPTION
        A splice that silently produced an unparseable script would only be
        discovered on an endpoint, where the failure looks like a broken
        installer. This is checked at build time instead.

        Returns @{ Valid; Errors }.
    #>
    param([Parameter(Mandatory)][string]$PackagePath)

    $errors = @()

    foreach ($name in Get-PackageScriptNames) {
        $path = Join-Path $PackagePath $name
        if (-not (Test-Path -LiteralPath $path)) {
            $errors += "$name is missing from the package."
            continue
        }

        $tokens = $null
        $parseErrors = $null
        [System.Management.Automation.Language.Parser]::ParseFile($path, [ref]$tokens, [ref]$parseErrors) | Out-Null

        foreach ($parseError in @($parseErrors)) {
            $errors += "$name line $($parseError.Extent.StartLineNumber): $($parseError.Message)"
        }

        $text = Get-Content -LiteralPath $path -Raw
        if ($text.Contains($script:RuntimeMarker)) {
            $errors += "$name still contains the runtime marker, so the runtime was never spliced in."
        }
        if ($text -notmatch 'function\s+Get-PackageConfiguration') {
            $errors += "$name does not contain the runtime, so it is not self-contained."
        }
    }

    return @{ Valid = ($errors.Count -eq 0); Errors = $errors }
}
